# # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: CI

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [10.x, 12.x]

#     steps:
#     - name: NodeJS Action Template
#       uses: bitoiu/node-js-action-template@v1.0
#     - name: Vuepress deploy
#       uses: jenkey2011/vuepress-deploy@1.0.1
#     - run: npm run docs:build
#     - run: cd docs/.vuepress/dist
#     - run: git init
#     - run: git add -A
#     - run: git commit -m 'deploy'
#     - run: git push -f git@github.com:ruiyoung/web.git master
#       env:
#         CI: true
